import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { NextUIProviders } from '@/components/providers/nextui';
import { ReactLenisProvider } from '@/components/providers/react-lenis';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next Sanity Template',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactLenisProvider>
          <NextUIProviders>{children}</NextUIProviders>
        </ReactLenisProvider>
      </body>
    </html>
  );
}
